name: Linting & formatting

on:
  push: 
    branches: [main]
  pull_request: 

  workflow_call: 

permissions:
  contents: write

jobs:
  clone-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v5

  check-formatting:
    runs-on: ubuntu-latest
    needs: clone-project

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check linting
        run: deno fmt --check .

  check-linting:
    runs-on: ubuntu-latest
    needs: clone-project

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check typing
        run: deno lint .
